### Stage 1: build ###
FROM node:lts-alpine AS build

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install

ENV PATH="./node_modules/.bin:$PATH" 

COPY . ./
RUN npm run build

# ### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
COPY --from=build /usr/src/app/dist/angularMDBClient /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]