# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todolist',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=b'2020-06-30'),
        ),
    ]
