# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200630_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-modify_date']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=b'2020-06-30T13:24'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='modify_date',
            field=models.DateTimeField(default=b'2020-06-30T13:24'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
