# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200630_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
